project:
  type: website

website:
  title: "Irena Papst, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - teaching.qmd
      - talks.qmd
    right:
      - href: cv.html
        text: CV
      - href: resume.html
        text: Resumé

format:
  html:
    theme: cosmo
    linkcolor: "#BD3829"
    monocolor: "#BD3829"
    css: styles.css
    toc: true

execute:
  freeze: auto



