project:
  type: website

website:
  title: "papsti.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - teaching.qmd
      - talks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



