project:
  type: website

website:
  title: "Irena Papst, PhD"
  navbar:
    left:
      - href: projects.qmd
        text: ":hammer: Projects"
      - href: teaching.qmd
        text: ":apple: Teaching"
      - href: talks.qmd
        text: ":loudspeaker: Talks"
    right:
      - href: cv.html
        text: CV
      - href: resume.html
        text: Resumé
      - href: https://github.com/papsti
        text: "GitHub"

format:
  html:
    theme: theme.scss
    toc: true

execute:
  freeze: auto



