project:
  type: website

website:
  title: "Irena Papst, PhD"
  navbar:
    left:
      - href: software.qmd
        text: ":hammer: Software"
      - href: teaching.qmd
        text: ":apple: Teaching"
      - href: talks.qmd
        text: ":loudspeaker: Talks"
      - href: community.qmd
        text: ":handshake: Community"

format:
  html:
    theme: theme.scss
    toc: true

execute:
  freeze: auto



